config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:show]

  scope :admin do
  	get '/login/', to: 'sessions#new'
  	post '/login/', to: 'sessions#create'
  	delete '/login/', to: 'sessions#destroy'

    put '/recipes/:id/publish', to: 'recipes#publish', as: 'recipe_publish'
    patch '/recipes/:id/publish', to: 'recipes#publish'
    get 'recipes/:id/preview', to: 'recipes#preview', as: 'recipe_preview'
  	resources :recipes, except: [:index, :show] do
      resources :ingredients, except: [:index, :show]
      resources :steps, except: [:index, :show]
    end
    resources :groceries, except: [:index, :show]
    get '/', to: 'recipes#admin', as: 'admin_root'
  end

  get 'measurements/selectbox', to: 'measurements#selectbox'
  get 'groceries/selectbox', to: 'groceries#selectbox'

  resources :recipes, only: [:index, :show]
  resources :groceries, only: [:index, :show]

  root 'admins#new'
end

app/views/admins/_admin.html.erb
<tr class='row clickable-row'>
	<td class='col-4'><%= link_to admin.full_name, edit_admin_path(admin), class: 'link-unstyled' %></td>
	<% if admin.discarded? %>
		<td class='col-2 text-center text-danger'><%= icon('fas', 'times-circle') %></td>
	<% else %>
		<td class='col-2 text-center text-success'><%= icon('fas', 'check-circle')%></td>
	<% end %>
	<td class='col-2'><%= admin.created_at.strftime("%-m-%-d-%Y")%></td>
	<td class='col-2 text-center'><%= admin.recipes.unpublished.count %></td>
	<td class='col-2 text-center'><%= admin.recipes.published.count %></td>
</tr>

app/views/admins/_form.html.erb
<div class='container' id='new-admin-form'>
	<%= bootstrap_form_for(@admin, url: (!!@admin.id ? admin_path(@admin) : admins_path), local: true, label_errors: true) do |f| %>
		<div class='form-row'>
			<%= f.text_field :first_name, wrapper: { class: 'col-6' }, placeholder: 'Required' %>
			<%= f.text_field :last_name, wrapper: { class: 'col-6' }, placeholder: 'Required' %>
		</div>
		<%= f.email_field :email, placeholder: 'Required' %>
		<%= f.password_field :password, placeholder: 'Required' %>
		<%= f.password_field :password_confirmation, placeholder: 'Required' %>
		<%= render partial: @submit, locals: { f: f } %>
	<% end %>
</div>

app/views/admins/_nav.html.erb
<div class='admin-nav'>
	<div class='container'>
		<ul class='nav'>
			<li class='nav-item'>
				<%= link_to (icon('fa','plus') << ' New'), new_admin_path, class: 'nav-link no-disable' %>
			</li>
			<li class='nav-item'>
				<%= link_to 'Your Account', edit_admin_path(@current_admin), class: 'nav-link no-disable' %>
			</li>
		</ul>
	</div>
</div>

app/views/admins/_submit_edit.html.erb
<div class='form-row'>
	<div class='col-6'>
		<%= f.submit 'Save Details', extra_class: 'btn-block' %>
	</div>
	<div class='col-6'>
		<%= link_to 'Close Account', admin_path(@admin), method: :delete, button: true, class: 'btn btn-block background-dark-red text-white', data: { confirm: 'Are you sure?' } %>
	</div>
</div>

app/views/admins/_submit_new.html.erb
<%= f.submit 'Save Details', extra_class: 'btn-block' %>

app/views/admins/_table.html.erb
<table class='table table-hover'>
	<tr class='row font-serif text-dark-red'>
		<th scope='col' class='col-4'>Name</th>
		<th scope='col' class='col-2 text-center'>Active?</th>
		<th scope='col' class='col-2'>Added</th>
		<th scope='col' class='col-2 text-center'>Drafted Recipes</th>
		<th scope='col' class='col-2 text-center'>Published Recipes</th>
	</tr>
	<%= render @admins %>
</table>

app/views/admins/edit.html.erb
<div class='row head-row'>
	<div class='col-12'>
		<h1 class='text-center'>Edit <%= @admin.full_name %>'s Account</h1>
	</div>
</div>
<div class='row'>
	<%= render partial: 'form' %>
</div>

app/views/admins/index.html.erb
<div class='row head-row' id='users-head'>
	<div class='col-12'>
		<h1 class='text-red font-serif'><%= icon('fa', 'id-badge', class: 'text-dark-teal') %> User Management</h1>
		<p class='lead'>Click a user below to edit or delete their account.</p>
	</div>
</div>
<div class='row' id='users-nav'>
	<%= render partial: 'nav' %>
</div>
<div class='row' id='users-body'>
	<div class='col-12' id='users-table'>
		<%= render partial: 'table' %>
	</div>
</div>

app/views/admins/new.html.erb
<div class='row head-row'>
	<div class='col-12'>
		<h1 class='text-center'>Create an Administrator Account</h1>
	</div>
</div>
<div class='row'>
	<%= render partial: 'form' %>
</div>