config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:show]

  scope :admin do
  	get '/login/', to: 'sessions#new'
  	post '/login/', to: 'sessions#create'
  	delete '/login/', to: 'sessions#destroy'

    put '/recipes/:id/publish', to: 'recipes#publish', as: 'recipe_publish'
    patch '/recipes/:id/publish', to: 'recipes#publish'
    get 'recipes/:id/preview', to: 'recipes#preview', as: 'recipe_preview'
  	resources :recipes, except: [:index, :show] do
      resources :ingredients, except: [:index, :show]
      resources :steps, except: [:index, :show]
    end
    resources :groceries, except: [:index, :show]
    get '/', to: 'recipes#admin', as: 'admin_root'
  end

  get 'measurements/selectbox', to: 'measurements#selectbox'
  get 'groceries/selectbox', to: 'groceries#selectbox'

  resources :recipes, only: [:index, :show]
  resources :groceries, only: [:index, :show]

  root 'admins#new'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	# roles - constant list
	RECIPE_ROLES = ['Small Bite','Beverage','Meat','Poultry','Seafood','Vegetable','Side Dish','Dessert']
	# associations
	belongs_to :author, class_name: 'Admin', foreign_key: :admin_id
	has_many :ingredients, dependent: :destroy
	has_many :groceries, through: :ingredients
	has_many :steps, dependent: :destroy
	# image support
	has_one_attached :photo
	# validations
	validates :dish_name, { presence: { message: 'cannot be blank' } , uniqueness: true }
	validates :author, presence: { message: 'cannot be blank' }
	validates :serves, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12, message: 'must be a number between 1 and 12' }
	validates :dish_role, inclusion: { in: self::RECIPE_ROLES , message: 'must be assigned a recognized role' }
	validates :photo, content_type: { in: ['image/png', 'image/jpg', 'image/jpeg'], message: 'must be a .png, .jpg or .jpeg file' }
	# publication validations
	validates :ingredients, presence: { message: 'must have at least one ingredient', on: :publish }
	validates :steps, presence: { message: 'must have at least one step in its directions', on: :publish }
	# scopes
	scope :published, -> { where("published_at IS NOT NULL") }
	scope :unpublished, -> { where("published_at IS NULL") }

	# prep time helpers
	def total_prep_time_in_seconds
		steps.map { |s| s.prep_time_in_seconds }.inject(:+)
	end

	def active_prep_time_in_seconds
		steps.active.map { |s| s.prep_time_in_seconds }.inject(:+)
	end

	def display_total_prep_time
		if total_prep_time_in_seconds > 3600
			"#{total_prep_time_in_seconds/3600} hours #{(total_prep_time_in_seconds.to_f/60.0).ceil} minutes"
		else
			"#{(total_prep_time_in_seconds.to_f/60.0).ceil} minutes"
		end
	end

	def display_active_prep_time
		if !active_prep_time_in_seconds
			"None"
		elsif active_prep_time_in_seconds > 3600
			"#{active_prep_time_in_seconds/3600} hours #{(active_prep_time_in_seconds.to_f/60.0).ceil} minutes"
		else
			"#{(active_prep_time_in_seconds.to_f/60.0).ceil} minutes"
		end
	end

	# role helper for icons
	def dish_role_as_icon
		case dish_role
		when 'Small Bite'
			'hotdog'
		when 'Beverage'
			'cocktail'
		when 'Meat'
			'hippo'
		when 'Poultry'
			'drumstick-bite'
		when 'Seafood'
			'fish'
		when 'Vegetable'
			'carrot'
		when 'Side Dish'
			'mortar-pestle'
		when 'Dessert'
			'cookie-bite'
		end
	end

	def published?
		!!published_at
	end

	# step order helpers
	def next_step_index
		steps.count + 1
	end

	def reindex_steps(added_index)
		index_counter = 1
		steps.order(step_order: :asc, updated_at: :desc).each do |step|
			index_counter += 1 if step.step_order == added_index
			if step.step_order != index_counter
				step.update_attribute(:step_order, index_counter)
			end
			index_counter += 1
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action only: [:new, :create, :admin] do
		authorize_admin
		@navbar = 'admin_navbar'
	end

	before_action only: [:edit, :update, :destroy, :publish] do
		authorize_recipe_owner(params[:id])
		@navbar = 'admin_navbar'
	end

	before_action only: [:preview] do
		authorize_recipe_owner(params[:id])
		@navbar = 'preview_navbar'
	end

	def index
	end

	def show
		@recipe = Recipe.includes(:steps, :ingredients).find(params[:id])
	end

	def new
		@recipe = Recipe.new
		@recipe_roles = Recipe::RECIPE_ROLES
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe_roles = Recipe::RECIPE_ROLES
		@recipe.author = current_admin
		if @recipe.save
			redirect_to edit_recipe_path(@recipe)
		else
			@errors = @recipe.errors.full_messages
			render :new
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
		@recipe_roles = Recipe::RECIPE_ROLES
		respond_to do |format|
			format.js
			format.html
		end
	end

	def update
		@recipe = Recipe.find(params[:id])
		@recipe_roles = Recipe::RECIPE_ROLES
		@recipe.update(recipe_params)
		if @recipe.save
			redirect_to edit_recipe_path(@recipe)
		else
			@alert = errors_alert("Your content could not be saved:\r\n\r\n",@recipe.errors.full_messages)
			respond_to do |format|
				format.html { render :edit }
				format.js { render :'recipes/errors' }
			end
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		redirect_to admin_root_path
	end

	def preview
		@recipe = Recipe.includes(:steps, :ingredients).find(params[:id])
		render :show
	end

	def publish
		@recipe = Recipe.find(params[:id])
		@recipe.published_at = DateTime.now
		if @recipe.save(context: :publish)
			respond_to do |format|
				format.js
				format.html { redirect_to admin_root_path }
			end
		else
			@alert = errors_alert("Your content could not be saved:\r\n\r\n",@recipe.errors.messages)
			respond_to do |format|
				format.js { render :'recipes/errors' }
			end
		end
	end

	def admin
		if params[:published]
			@recipes = Recipe.where(author: current_admin).order(updated_at: :desc)
		elsif params[:all]
			@recipes = Recipe.all.order(updated_at: :desc)
		else
			@recipes = Recipe.unpublished.where(author: current_admin).order(updated_at: :desc)
		end
		respond_to do |format|
			format.js
			format.html
		end
	end

	private
	def recipe_params
		params.require(:recipe).permit(:dish_name, :dish_role, :description, :serves, :photo)
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_admin_recipe.html.erb
<tr class='row clickable-row'>
  <td class='col-4'><%= link_to recipe.dish_name, edit_recipe_path(recipe), class: 'link-unstyled' %></td>
  <% if recipe.published? %>
    <td class='col-2 text-center text-success'><%= icon('fas','check-circle') %></td>
  <% else %>
    <td class='col-2 text-center text-danger'><%= icon('fas','times-circle') %></td>
  <% end %>
  <td class='col-2'><%= time_ago_in_words(recipe.updated_at) %> ago</td>
  <td class='col-2 text-center'><%= recipe.ingredients.count %></td>
  <td class='col-2 text-center'><%= recipe.steps.count %></td>
</tr>

app/views/recipes/_admin_table.html.erb
<table class='table table-hover'>
  <tr class='row font-serif text-dark-red'>
    <th scope='col' class='col-4'>Dish</th>
    <th scope='col' class='col-2 text-center'>Published?</th>
    <th scope='col' class='col-2'>Last Edited</th>
    <th scope='col' class='col-2 text-center'>Ingredients</th>
    <th scope='col' class='col-2 text-center'>Instructions</th>
  </tr>
  <% @recipes.each do |recipe| %>
    <%= render partial: 'admin_recipe', locals: { recipe: recipe } %>
  <% end %>
</table>

app/views/recipes/_form.html.erb
<div class='container wizard-content' id='recipe-form'>
	<h4 class='font-cursive'>Dish Description</h4>
	<%= bootstrap_form_for(@recipe, url: (!!@recipe.id ? recipe_path(@recipe) : recipes_path), inline_errors: false, remote: (!!@recipe.id)) do |f| %>
		<div class='form-row'>
			<%= f.text_field :dish_name, wrapper: { class: 'col-3' }, placeholder: 'Required' %>
			<%= f.select(:dish_role, @recipe_roles.map { |role| [role, role] }, wrapper: { class: 'col-3' }) %>
			<%= f.number_field :serves, wrapper: { class: 'col-3' }, in: 1..12, step: 1  %>
			<%= f.file_field :photo, wrapper: { class: 'col-3' }, custom: true %>
		</div>
		<%= f.text_area :description, rows: 8 %>
		<%= f.submit 'Add Details', extra_class: 'btn-block font-cursive background-light-teal text-black' %>
	<% end %>
</div>

app/views/recipes/_ingredient_wizard.html.erb
<div class='container wizard-content'>
	<div class='row'>
		<div class='col-4' id='ingredient-list'>
			<%= render partial: 'ingredients/list', locals: { ingredients: @recipe.ingredients } %>
		</div>
		<div class='col-8' id='ingredient-form'>
			<%= render partial: 'ingredients/form' %>
		</div>
	</div>
</div>

app/views/recipes/_step_wizard.html.erb
<div class='container wizard-content'>
	<div class='row'>
		<div class='col-4' id='step-list'>
			<%= render partial: 'steps/list', locals: { steps: @recipe.steps.order(:step_order) } %>
		</div>
		<div class='col-8' id='step-form'>
			<%= render partial: 'steps/form' %>
		</div>
	</div>
</div>

app/views/recipes/_tabs.html.erb
<div class='wizard-nav'>
	<div class='container'>
		<ul class='nav'>
			<li class='nav-item'>
				<%= link_to 'Dish Information', edit_recipe_path(@recipe), remote: true, class: "nav-link#{@ingredient || @step ? '' : ' active'}" %>
			</li>
			<li class='nav-item'>
				<%= link_to 'Ingredients', new_recipe_ingredient_path(@recipe), remote: true, class: "nav-link#{@ingredient ? ' active' : ''}" %>
			</li>
			<li class='nav-item'>
				<%= link_to 'Preparation', edit_recipe_path(@recipe), remote: true, class: 'nav-link disabled' %>
			</li>
		</ul>
	</div>
</div>

app/views/recipes/_wizard_head.html.erb
<div class='col-12'>
	<h1 class='text-red font-serif'><%= icon('fa', 'edit', class: 'text-dark-teal') %> Recipe Editor</h1>
	<p class='lead' id='wizard-text'>Add ingredients, directions and information about the dish.</p>
</div>

app/views/recipes/admin.js.erb
$("#recipes-table").html("<%= j render partial: 'admin_table' %>");

app/views/recipes/edit.html.erb
<div class='row head-row' id='wizard-head'>
	<%= render partial: 'wizard_head' %>
</div>
<div class='row' id ='wizard-nav'>
	<%= render partial: 'wizard_nav' %>
</div>
<div class='row' id='wizard-content'>
	<%= render partial: 'form' %>
</div>

app/views/recipes/edit.js.erb
$("#wizard-content").html("<%= j render partial: 'recipes/form' %>");

app/views/recipes/errors.js.erb
alert("<%= j @alert %>");

app/views/recipes/new.html.erb
<div class='row head-row' id='wizard-head'>
	<div class='col-12'>
		<h1 class='text-red font-serif'><%= icon('fa', 'edit', class: 'text-dark-teal') %>Recipe Editor</h1>
		<p class='lead' id='wizard-text'>Enter the name and description of the dish to get started.</p>
	</div>
</div>
<div class='row' id ='wizard-nav'>
  <div class='wizard-nav'>
    <div class='container'>
      <ul class='nav'>
        <li class='nav-item'>
          <%= link_to 'Description', '#', class: 'nav-link disabled' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Ingredients', '#', class: 'nav-link disabled' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Preparation', '#', class: 'nav-link disabled' %>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class='row' id='wizard-content'>
	<%= render partial: 'form' %>
</div>

app/views/recipes/publish.js.erb
window.location.href = "<%= j admin_root_path %>";

app/views/recipes/show.html.erb
<div class='row head-row' id='recipe-head'>
  <div class='col-4'>
    <div id='recipe-image' class='head-collapse-content'>
      <%= image_tag url_for(@recipe.photo), class: 'img-fluid', alt: 'placeholder.jpg' %>
    </div>
  </div>
  <div class='col-8'>
    <button class='navbar-toggler text-dark-red float-right' id='head-collapse-button'>
      <%= icon('fas','minus-circle') %>
    </button>
    <h1 id='recipe-title' class='text-red font-serif'><%= icon('fas', @recipe.dish_role_as_icon, class: 'text-dark-teal') %> <%= @recipe.dish_name %>
    </h1>
    <div class='head-collapse-content'>
      <p id='recipe-byline' class='text-dark-red font-serif'>
        <span><%= @recipe.dish_role %></span>
        <span>&bull;</span>
        <span><%= @recipe.author.full_name %></span>
        <span>&bull;</span>
        <span><%= @recipe.published? ? @recipe.published_at.strftime("%B %-d, %Y") : DateTime.now.strftime("%B %-d, %Y") %></span>
      </p>
      <p><%= @recipe.description %></p>
    </div>
  </div>
</div>
<div class='row' id='recipe-stats'>
  <div class='col-12'>
    <dl class='row'>
      <dt class='col-2 text-dark-red font-serif'>Serves:</dt>
      <dd class='col-2 text-right'><%= @recipe.serves %></dd>
      <dt class='col-2 text-dark-red font-serif'>Total Prep Time:</dt>
      <dd class='col-2 text-right'><%= @recipe.display_total_prep_time %></dd>
      <dt class='col-2 text-dark-red font-serif'>Active Prep Time:</dt>
      <dd class='col-2 text-right'><%= @recipe.display_active_prep_time %></dd>
    </dl>
  </div>
</div>
<div class='row' id='recipe-body'>
  <div class='col-4' id='recipe-ingredients'>
    <h3 class='text-red font-serif'>Ingredients</h3>
    <ul class='list-unstyled'>
      <%= render @recipe.ingredients %>
    </ul>
  </div>
  <div class='col-8' id='recipe-directions'>
    <h3 class='font-serif text-red'>Instructions</h3>
    <ul class='list-unstyled'>
      <%= render @recipe.steps.order(step_order: :asc) %>
    </ul>
  </div>
</div>