config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:show]

  scope :admin do
  	get '/login/', to: 'sessions#new'
  	post '/login/', to: 'sessions#create'
  	delete '/login/', to: 'sessions#destroy'

    put '/recipes/:id/publish', to: 'recipes#publish', as: 'recipe_publish'
    patch '/recipes/:id/publish', to: 'recipes#publish'
    get 'recipes/:id/preview', to: 'recipes#preview', as: 'recipe_preview'
  	resources :recipes, except: [:index, :show] do
      resources :ingredients, except: [:index, :show]
      resources :steps, except: [:index, :show]
    end
    resources :groceries, except: [:index, :show]
    get '/', to: 'recipes#admin', as: 'admin_root'
  end

  get 'measurements/selectbox', to: 'measurements#selectbox'
  get 'groceries/selectbox', to: 'groceries#selectbox'

  resources :recipes, only: [:index, :show]
  resources :groceries, only: [:index, :show]

  root 'admins#new'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	# associations
	belongs_to :measurement
	belongs_to :grocery
	belongs_to :recipe
	# validations
	validates :recipe, presence: { message: 'must be assigned' }
	validates :grocery, { 
		uniqueness: { scope: :recipe , message: 'is already an ingredient of this recipe' }, 
		presence: { message: 'must be assigned' }
	}
	validates :measurement, presence: { message: 'must be assigned' }
	validates :amount, numericality: { greater_than: 0 , message: 'must be a whole number or fraction with denominator 2,3,4 or 8' }
	validates :comment, length: { maximum: 100 }
	validate :common_amounts_only

	# display helpers
	def display_amount
		if amount < 1 
			amount.to_r.to_s
		elsif amount % 1 != 0
			[amount.to_i.to_s, (amount % 1).to_r.to_s].join(' ')
		else
			amount.to_i.to_s
		end
	end

	def display_measurement
		measurement_override ? measurement_override.downcase : measurement.abbreviation
	end

	def display_comment
		comment > '' ? (', ' << comment) : ''
	end

	def display_ingredient_list
		"#{display_amount} #{display_measurement} #{grocery.grocery_name}#{display_comment}"
	end

	private
	# callbacks
	before_save do |ingredient|
		measurement_override = nil if measurement.measurement_name != "Pieces"
	end

	after_save do |ingredient|
		recipe.update_attribute(:updated_at, DateTime.now)
	end

	# custom validation
	def common_amounts_only
		if !/\A\d*\/[1,2,3,4,8]\z/.match(amount.to_r.to_s)
			errors.add(:amount, 'must be a whole number or fraction with denominator 2,3,4 or 8')
		end
	end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action do
		authorize_recipe_owner(params[:recipe_id])
		@navbar = 'admin_navbar'
	end

	def new
		@recipe = Recipe.includes(:ingredients).find(params[:recipe_id])
		@grocery_types = Grocery::GROCERY_TYPES
		@grocery_type = @grocery_types.first
		@groceries = Grocery.where(grocery_type: @grocery_type).order(:grocery_name).pluck(:grocery_name, :id)
		@measurement_types = Measurement.measurement_types
		@measurement_type = @measurement_types.first
		@measurements = Measurement.where(measurement_type: @measurement_type).order(:measurement_type, :measurement_name).pluck(:measurement_name, :id)
		@ingredient = Ingredient.new
		respond_to do |format|
			format.js
			format.html
		end
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		debugger
		if @ingredient.save
			@recipe = Recipe.includes(:ingredients).find(params[:recipe_id])
			@grocery_types = Grocery::GROCERY_TYPES
			@grocery_type = @grocery_types.first
			@groceries = Grocery.where(grocery_type: @grocery_type).order(:grocery_name).pluck(:grocery_name, :id)
			@measurement_types = Measurement.measurement_types
			@measurement_type = @measurement_types.first
			@measurements = Measurement.where(measurement_type: @measurement_type).order(:measurement_type, :measurement_name).pluck(:measurement_name, :id)
			@ingredient = Ingredient.new
			respond_to do |format|
				format.js { render :new }
				format.html { redirect_to new_recipe_ingredient_path(@recipe) }
			end
		else
			@alert = errors_alert("Your content could not be saved:\r\n\r\n",@ingredient.errors.full_messages)
			respond_to do |format|
				format.js { render :'recipes/errors' }
				format.html { render :new }
			end
		end
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
		@recipe = @ingredient.recipe
		@grocery_types = Grocery::GROCERY_TYPES
		@grocery_type = @ingredient.grocery.grocery_type
		@groceries = Grocery.where(grocery_type: @grocery_type).order(:grocery_name).pluck(:grocery_name, :id)
		@measurement_types = Measurement.measurement_types
		@measurement_type = @ingredient.measurement.measurement_type
		@measurements = Measurement.where(measurement_type: @measurement_type).order(:measurement_type, :measurement_name).pluck(:measurement_name, :id)
		respond_to do |format|
			format.js { render :new }
			format.html { render :new }
		end
	end

	def update
		@ingredient = Ingredient.find(params[:id])
		@recipe = @ingredient.recipe
		@grocery_types = Grocery::GROCERY_TYPES
		@measurement_types = Measurement.measurement_types
		@ingredient.update(ingredient_params)
		if @ingredient.save
			@grocery_type = @grocery_types.first
			@groceries = Grocery.where(grocery_type: @grocery_type).order(:grocery_name).pluck(:grocery_name, :id)
			@ingredient = Ingredient.new
			@measurement_type = @measurement_types.first
			@measurements = Measurement.where(measurement_type: @measurement_type).order(:measurement_type, :measurement_name).pluck(:measurement_name, :id)
			respond_to do |format|
				format.js { render :new }
				format.html { redirect_to new_recipe_ingredient_path(@recipe) }
			end
		else
			@alert = errors_alert("Your content could not be saved:\r\n\r\n",@ingredient.errors.full_messages)
			respond_to do |format|
				format.js { render :'recipes/errors' }
				format.html { render :new }
			end
		end
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy
		respond_to do |format|
			@recipe = Recipe.includes(:ingredients).find(params[:recipe_id])
			format.js
			format.html { redirect_to new_recipe_ingredient_path(@recipe) }
		end
	end

	private
	def ingredient_params
		params.require(:ingredient).permit(:recipe_id, :grocery_id, :measurement_id, :amount, :measurement_override, :comment)
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class='container' id='new-ingredient-form'>
	<h4 class='font-cursive'>Ingredient Picker</h4>
	<%= bootstrap_form_for(@ingredient, url: (!!@ingredient.id ? recipe_ingredient_path(@recipe, @ingredient) : recipe_ingredients_path(@recipe)), remote: true, inline_errors: false) do |f| %>
		<%= f.hidden_field :recipe_id, value: @recipe.id %>
		<div class='form-row' id='groceries-row'>
			<%= render partial: 'groceries/ingredient_form_row' %>
		</div>
		<div class='form-row' id='measurements-row'>
			<%= render partial: 'measurements/ingredient_form_row' %>
		</div>
		<%= f.text_field :comment, help: 'Keep it brief, e.g. "chopped"' %>
		<%= f.submit 'Update Ingredients', extra_class: 'btn-block font-cursive background-teal text-black' %>
	<% end %>
</div>

app/views/ingredients/_ingredient.html.erb
<li><%= ingredient.display_ingredient_list %></li>

app/views/ingredients/_list.html.erb
<div class='container'>
	<h4 class='font-cursive'>Ingredients So Far</h4>
	<ul class='list-unstyled ingredient-wizard-list'>
    <% ingredients.each do |ingredient| %>
		  <%= render partial: 'wizard_ingredient', locals: { ingredient: ingredient } %>
    <% end %>
	</ul>
</div>

app/views/ingredients/_wizard_ingredient.html.erb
<li class='wizard-list-item font-cursive'>
	<span class='wizard-list-display'><%= ingredient.display_ingredient_list %></span>
	<span class='float-right'>
		<%= link_to icon('fas', 'pen'), edit_recipe_ingredient_path(@recipe, ingredient), remote: true %>
		<%= link_to icon('fas', 'times'), recipe_ingredient_path(@recipe, ingredient), method: :delete, remote: true, data: { confirm: 'Are you sure you want to delete this?' } %>
	</span>
</li>

app/views/ingredients/destroy.js.erb
$("#ingredient-list").html("<%= j render partial: 'list', locals: { ingredients: @recipe.ingredients } %>");

app/views/ingredients/new.html.erb
<div class='row head-row' id='wizard-head'>
	<%= render partial: 'recipes/wizard_head' %>
</div>
<div class='row' id ='wizard-tabs'>
	<%= render partial: 'recipes/wizard_nav' %>
</div>
<div class='row' id='wizard-content'>
	<%= render partial: 'recipes/ingredient_wizard' %>
</div>

app/views/ingredients/new.js.erb
$("#wizard-nav").html("<%= j render partial: 'recipes/wizard_nav' %>");
$("#wizard-content").html("<%= j render partial: 'recipes/ingredient_wizard' %>");