config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:show]

  scope :admin do
  	get '/login/', to: 'sessions#new'
  	post '/login/', to: 'sessions#create'
  	delete '/login/', to: 'sessions#destroy'

    put '/recipes/:id/publish', to: 'recipes#publish', as: 'recipe_publish'
    patch '/recipes/:id/publish', to: 'recipes#publish'
    get 'recipes/:id/preview', to: 'recipes#preview', as: 'recipe_preview'
  	resources :recipes, except: [:index, :show] do
      resources :ingredients, except: [:index, :show]
      resources :steps, except: [:index, :show]
    end
    resources :groceries, except: [:index, :show]
    get '/', to: 'recipes#admin', as: 'admin_root'
  end

  get 'measurements/selectbox', to: 'measurements#selectbox'
  get 'groceries/selectbox', to: 'groceries#selectbox'

  resources :recipes, only: [:index, :show]
  resources :groceries, only: [:index, :show]

  root 'admins#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def current_admin
		@current_admin ||= Admin.kept.find(session[:admin]) if session[:admin]
	end

	private
	def authorize_admin
		if !current_admin
			flash[:notice] = 'You must be logged in to access this.'
			redirect_to login_path
		end
	end

	def authorize_account_owner
		if !current_admin
			flash[:notice] = 'You must be logged in to access this.'
			redirect_to login_path and return
		elsif	!(params[:id] == current_admin.id || current_admin.is_super_admin?)
			flash[:alert] = 'You are not authorized to access this.'
			redirect_to :back
		end
	end

	def authorize_super_admin
		if !current_admin
			flash[:notice] = 'You must be logged in to access this.'
			redirect_to login_path and return
		elsif !current_admin.is_super_admin?
			flash[:alert] = 'You are not authorized to access this.'
			redirect_to :back
		end
	end

	def authorize_recipe_owner(id)
		@recipe ||= Recipe.find(id)
		if @recipe && !current_admin
			flash[:notice] = 'You must be logged in to access this.'
			redirect_to login_path and return
		elsif @recipe && !(@recipe.author == current_admin || current_admin.is_super_admin?)
			flash[:alert] = 'You are not authorized to access this.'
			redirect_to :back
		end
	end

	def errors_alert(header, errors)
		errors.each do |error|
			header << "* " << error << "\r\n"
		end
		header
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin_navbar.html.erb
<nav class='navbar navbar-expand-md fixed-top background-dark-red' id='site-nav'>
	<%= link_to 'My Recipe Site', root_path, class: 'navbar-brand font-serif text-white' %>
	<button class='navbar-toggler navbar-toggler-right collapse-button' type='button' data-toggle='collapse' data-target='#navbar-supported-content'>
    <%= icon('fa', 'chevron-down', class: 'text-white') %>
  </button>
	<div class='collapse navbar-collapse' id='navbar-supported-content'>
		<ul class='navbar-nav'>
			<li class='nav-item'><%= link_to 'Recipes', admin_root_path, class: 'nav-link text-white' %></li>
			<% if @current_admin.is_super_admin? %>
				<li class='nav-item'><%= link_to 'Users', admins_path, class: 'nav-link text-white' %></li>
			<% else %>
				<li class='nav-item'><%= link_to 'Account', admin_edit_path(@current_admin), class: 'nav-link text-white' %></li>
			<% end %>
			<li class='nav-item'><%= link_to 'Logout', login_path, method: :delete, class: 'nav-link text-white' %></li>
		</ul>
	</div>
</nav>

app/views/application/_login_navbar.html.erb
<nav class='navbar navbar-expand-md fixed-top background-dark-red'>
	<%= link_to 'My Recipe Site', root_path, class: 'navbar-brand font-serif text-white' %>
</nav>

app/views/application/_preview_navbar.html.erb
<nav class='navbar navbar-expand-md fixed-top background-dark-red'>
  <%= link_to 'My Recipe Site', root_path, class: 'navbar-brand font-serif text-white' %>
  <span class='navbar-text text-white'><small><em>You are viewing this recipe in preview mode.</em></small></span>
  <button class='navbar-toggler navbar-toggler-right' type='button' data-toggle='collapse' data-target='#navbar-supported-content'>
    <%= icon('fa', 'chevron-down', class: 'text-white') %>
  </button>
  <div class='collapse navbar-collapse' id='navbar-supported-content'>
    <ul class='navbar-nav'>
      <li class='nav-item'><%= link_to (icon('fas','check-circle') << ' Publish'), recipe_publish_path(@recipe), method: :put, class: 'nav-link text-white' %></li>
      <li class='nav-item'><%= link_to 'Go Back', :back, class: 'nav-link text-white' %></li>
    </ul>
  </div>
</nav>